// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3P3wor8x60ha9yH82XX_XGx8hrxZ6Cs8',
    appId: '1:386156922439:web:a64a5f21cc4336e6e55362',
    messagingSenderId: '386156922439',
    projectId: 'e-commerce-app-100a9',
    authDomain: 'e-commerce-app-100a9.firebaseapp.com',
    storageBucket: 'e-commerce-app-100a9.appspot.com',
    measurementId: 'G-WWF3L5Y3H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1oO4N0nkz2zs7fI-OOmQ8RwVktRfp4A',
    appId: '1:386156922439:android:3125a0b0c6ceaf33e55362',
    messagingSenderId: '386156922439',
    projectId: 'e-commerce-app-100a9',
    storageBucket: 'e-commerce-app-100a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAE1-bhU-WTeVW7U1xFPkbgyUUYwuOaFs',
    appId: '1:386156922439:ios:3f75985bd0eada54e55362',
    messagingSenderId: '386156922439',
    projectId: 'e-commerce-app-100a9',
    storageBucket: 'e-commerce-app-100a9.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAE1-bhU-WTeVW7U1xFPkbgyUUYwuOaFs',
    appId: '1:386156922439:ios:3f75985bd0eada54e55362',
    messagingSenderId: '386156922439',
    projectId: 'e-commerce-app-100a9',
    storageBucket: 'e-commerce-app-100a9.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
